// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Page$Cristeaxyz = require("./Page.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Page$Cristeaxyz.make("Hello Word!", /* array */[])), "index");

/*  Not a pure module */
